import OpenAI from "openai";
import dotenv from "dotenv";

dotenv.config();

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

import { CLASSIFIER_PROMPT } from "./prompts/index.js";

/**
 * Classifies an AI response into a specific category with reasoning.
 * @param {string} userQuestion - The original message from the user.
 * @param {string} aiResponse - The response generated by the primary AI.
 * @returns {Promise<object>} - { category, reason }
 */
export const classifyResponse = async (userQuestion, aiResponse) => {
    try {
        const prompt = CLASSIFIER_PROMPT
            .replace("{USER_QUESTION}", userQuestion)
            .replace("{AI_RESPONSE}", aiResponse);

        const completion = await openai.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [{ role: "user", content: prompt }],
            temperature: 0,
            response_format: { type: "json_object" }
        });

        const result = JSON.parse(completion.choices[0].message.content.trim());
        console.log(`[AI-CLASSIFIER] Category: ${result.category}, Reason: ${result.reason}`);

        return result;
    } catch (err) {
        console.error("[AI-CLASSIFIER] Error:", err.message);
        return { category: "NORMAL", reason: "Error in classification" };
    }
};
