import OpenAI from "openai";
import dotenv from "dotenv";

dotenv.config();

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

const CLASSIFIER_PROMPT = `
You are a Response Classifier. Your job is to analyze an AI response to a user's question and determine the category of the response.

CATEGORIES:
1. MISSING_KNOWLEDGE: The AI explicitly states it does not have the answer/access to info.
2. OUT_OF_SCOPE: The user asked something unrelated to the hospital/business (e.g. cooking, coding).
3. URGENT: The user is reporting an emergency, a critical problem, or severe dissatisfaction.
4. NEGATIVE_SENTIMENT: The user seems frustrated, angry, or upset.
5. NORMAL: A standard helpful response.

IMPORTANT: 
- Return your answer as a JSON object with two fields: "category" and "reason".
- "reason" should be a very brief (3-5 words) explanation of why you chose that category.
- If multiple categories apply, pick the most significant (URGENT > MISSING_KNOWLEDGE > OUT_OF_SCOPE).

USER QUESTION: "{USER_QUESTION}"
AI RESPONSE: "{AI_RESPONSE}"

Example Result: {"category": "MISSING_KNOWLEDGE", "reason": "No info on cataract pricing"}

RESULT:`;

/**
 * Classifies an AI response into a specific category with reasoning.
 * @param {string} userQuestion - The original message from the user.
 * @param {string} aiResponse - The response generated by the primary AI.
 * @returns {Promise<object>} - { category, reason }
 */
export const classifyResponse = async (userQuestion, aiResponse) => {
    try {
        const prompt = CLASSIFIER_PROMPT
            .replace("{USER_QUESTION}", userQuestion)
            .replace("{AI_RESPONSE}", aiResponse);

        const completion = await openai.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [{ role: "user", content: prompt }],
            temperature: 0,
            response_format: { type: "json_object" }
        });

        const result = JSON.parse(completion.choices[0].message.content.trim());
        console.log(`[AI-CLASSIFIER] Category: ${result.category}, Reason: ${result.reason}`);

        return result;
    } catch (err) {
        console.error("[AI-CLASSIFIER] Error:", err.message);
        return { category: "NORMAL", reason: "Error in classification" };
    }
};
