import { CLASSIFIER_PROMPT } from "./prompts/index.js";
import { callAI } from "./coreAi.js";

/**
 * Classifies an AI response into a specific category with reasoning.
 * @param {string} userQuestion - The original message from the user.
 * @param {string} aiResponse - The response generated by the primary AI.
 * @param {string} [tenant_id] - Optional tenant ID to resolve model selection.
 * @returns {Promise<object>} - { category, reason }
 */
export const classifyResponse = async (
  userQuestion,
  aiResponse,
  tenant_id = null,
) => {
  try {
    const prompt = CLASSIFIER_PROMPT.replace(
      "{USER_QUESTION}",
      userQuestion,
    ).replace("{AI_RESPONSE}", aiResponse);

    const result = await callAI({
      messages: [{ role: "user", content: prompt }],
      tenant_id,
      source: "classifier",
      temperature: 0,
      responseFormat: { type: "json_object" },
    });

    const parsed = JSON.parse(result.content);
    console.log(
      `[AI-CLASSIFIER] Category: ${parsed.category}, Reason: ${parsed.reason}`,
    );

    return parsed;
  } catch (err) {
    console.error("[AI-CLASSIFIER] Error:", err.message);
    return { category: "NORMAL", reason: "Error in classification" };
  }
};
