import db from "../../database/index.js";

const LOG_ATTRIBUTES = [
  "id",
  "request_id",
  "tenant_id",
  "user_id",
  "actor_type",
  "actor_name",
  "actor_email",
  "actor_role",
  "user_type",
  "method",
  "original_url",
  "route_path",
  "module",
  "status_code",
  "success",
  "duration_ms",
  "ip_address",
  "forwarded_for",
  "country",
  "region",
  "city",
  "timezone",
  "isp",
  "user_agent",
  "browser",
  "browser_version",
  "os",
  "os_version",
  "device_type",
  "device_vendor",
  "device_model",
  "referer",
  "origin",
  "accept_language",
  "query_json",
  "body_keys_json",
  "metadata_json",
  "error_message",
  "createdAt",
  "updatedAt",
];

const mapLogRecord = (log) => ({
  id: log.id,
  request_id: log.request_id,
  tenant_id: log.tenant_id,
  user_id: log.user_id,
  actor_type: log.actor_type,
  actor_name: log.actor_name,
  actor_email: log.actor_email,
  actor_role: log.actor_role,
  user_type: log.user_type,
  method: log.method,
  original_url: log.original_url,
  route_path: log.route_path,
  module: log.module,
  status_code: log.status_code,
  success: log.success,
  duration_ms: log.duration_ms,
  ip_address: log.ip_address,
  forwarded_for: log.forwarded_for,
  country: log.country,
  region: log.region,
  city: log.city,
  timezone: log.timezone,
  isp: log.isp,
  user_agent: log.user_agent,
  browser: log.browser,
  browser_version: log.browser_version,
  os: log.os,
  os_version: log.os_version,
  device_type: log.device_type,
  device_vendor: log.device_vendor,
  device_model: log.device_model,
  referer: log.referer,
  origin: log.origin,
  accept_language: log.accept_language,
  query_json: log.query_json,
  body_keys_json: log.body_keys_json,
  metadata_json: log.metadata_json,
  error_message: log.error_message,
  created_at: log.createdAt,
  updated_at: log.updatedAt,
});

export const getApiRequestLogsService = async () => {
  const rows = await db.ApiRequestLogs.findAll({
    attributes: LOG_ATTRIBUTES,
    order: [["createdAt", "DESC"]],
    limit: 1000,
  });

  return {
    logs: rows.map((row) => mapLogRecord(row.get({ plain: true }))),
  };
};
